# Generated by Django 5.2.5 on 2025-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='descripcion',
            field=models.CharField(default='Sin Descripcion', max_length=250),
        ),
    ]
