# Generated by Django 5.2.5 on 2025-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_videojuegos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='descripcion',
            field=models.CharField(default='Sin Descripcion', max_length=500),
        ),
    ]
