# Generated by Django 5.2.5 on 2025-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_videojuegos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='desarrollador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
