# Generated by Django 5.2.5 on 2025-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_videojuegos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
