# Generated by Django 5.2.5 on 2025-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_videojuegos_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_juegos'),
        ),
    ]
