# Generated by Django 5.2.5 on 2025-08-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_videojuegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_juegos'),
        ),
    ]
